BACKUP_VOLNAME ?= GREGTHUMB5
#BACKUP_VOLNAME ?= GREGTHUMB7
#BACKUP_VOLNAME ?= GREGBACK1

#BACKUP_DIRECTORY ?= Backup/ProjectsD/Minecraft
BACKUP_DIRECTORY ?= Minecraft

BACKUP_VOL := /Volumes/$(BACKUP_VOLNAME)
BACKUP_SUBDIR := $(BACKUP_DIRECTORY)/$(PROJECT)
BACKUP_DIR := $(BACKUP_VOL)/$(BACKUP_SUBDIR)
