// Autogenerated by geninfo, do not edit

package gcewing.projectblue;

public class Info {
	static final String modName = "Project Blue";
	static final String modID = "ProjectBlue";
	//static final String modPackage = "";
	static final String versionNumber = "1.1.6";
	static final String versionBounds = "[1.1,1.2)";
}
